name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt install
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi

    - name: dpkg
      run: dpkg -L gcc-arm-none-eabi
      
    - name: make
      run: make CC=/usr/bin/gcc-arm-none-eabi PRODUCT=sgm775 MODE=debug firmware-scp_ramfw
        
    
